title: "SYSEN 5630: Clinical Natural Language Processing and Large Language Models"
description: "Jan. 21, 2025 - May 6, 2025, 5:00-6:15 pm East Time on Tuesdays and Thursdays | 
              Remote"
theme: jekyll-theme-cayman
